ifeq ($(CONFIG_SPLIT_VIDEO_CMD_MODE_INTERFACE),y)
obj-$(CONFIG_FB_BRCM_KONA) += lcd_clock_video.o
else
obj-$(CONFIG_FB_BRCM_KONA) += lcd_clock.o
endif
obj-$(CONFIG_LCD_NT35510_SUPPORT) += nt35510_dsi.o
obj-$(CONFIG_LCD_S6E63M0X_SUPPORT) += s6e63m0x3_dsi.o smart_mtp_s6e63m0_dsi.o
